import React, { useEffect, useState } from "react";
import { ListComponent, ListTitle } from "../../components/List/List";
import { Panel } from "../../components/Panel/Panel";
import { HistoryItem, ListItem, TreeNodeType } from "../../types";
import s from "./customerdetailspage.module.scss";
import classnames from 'classnames';
import { Button } from "../../components/Button/Button";
import { Tag } from "../../components/Tag/Tag";
import { SimpleTree } from "../../components/Tree/SimpleTree";
import { Bar } from "react-chartjs-2";
import { HistoryList } from "../../components/HistoryList/HistoryList";
import { DropdownButton } from "components/DropdownButton/DropdownButton";

const TEST_DATA = {
  logo: 'https://w7.pngwing.com/pngs/980/413/png-transparent-apple-logo-business-iphone-apple-heart-computer-logo.png',

  partyType: '2',
  organizationName: "Apple Inc.",

  firstGivenName: 'Anna',

  addressLine1: "1 Westport, Portola Valley, PA 37142",
  addressLine2: "",
  addressLine3: "",
  cityName: "Leroy City",
  countryName: "TX 49787",
  stateProvince: "Loma Linda",
  postalCode: "89456",
  country: "",
  cityAreaDistrictName: "",
  phoneFaxType: "",
  phoneFaxRole: "",
  countryCode: "",
  phoneFaxNumber: "102-262-4196",
  extension: "",
  prefferedIndicator: false,

  phone: '1-375-423-8400',

  industrySegment: "",
  internalIndustrySegment: "",
  industryVertical: "",
  internalIndustryVertical: "",
  externalIdentifierType: "",
  status: "",
  identifierValue: "",
  identifierCountry: "",
  identifiedHeadquarterIndicator: false,
  globalUltimateParentIndicator: false,
  domesticUltimateParentIndicator: false,
  parentIndicator: false,

  name: 'Apple, Inc.',
  companyMarket: 'Consumer Electronics',
  ceo: 'Tim Cook',
  headquarters: 'Cupertino, California, USA',
  employees: '‎100,001+',
  revenue: '‎US$260.174 billion',
  locations: '‎511 retail stores',
  websiteUrl: 'http://www.apple.com',
  netIncome: 'US$55.256 billion',
  image: 'https://pbs.twimg.com/profile_images/1276481413127299072/F_itR06f_400x400.png',
  businessName: 'Apple',
  autoGeneratedSequencial: 'AppleID_17253',
  entityUri: 'MOKIZHB',
  companyType: '‎PUBLIC',
  ticker: 'APPL',
  isSubsidiary: 'FALSE',
  duns: '2460786',

  potencialMatches: [
    {name: 'IBM', logo: 'https://pbs.twimg.com/profile_images/1276481413127299072/F_itR06f_400x400.png', type: 'Organization'}
  ]
};

const TEST_EMPLOYEE_LIST = [
  {
    name: "Riley Cooper",
    description: "Account Executive",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Rahul Malviya",
    description: "Account Manager",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Jumaima Al Nour",
    description: "Executive Sponsor",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Faadi Al Rahman",
    description: "Sales Manager",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Maria Trofimova",
    description: "Pre-sales Consultant",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Faadi Al Rahman",
    description: "Sales Manager",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
];

const TEST_ACCOUNT_TEAN = [
  {
    name: "Lacara Jones",
    description: "Account Executive",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Herse Hedman",
    description: "Account Manager",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Farrokh Rastegar",
    description: "Executive Sponsor",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Dominik Doudny",
    description: "Pre-sales Consultant",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Malin Quist",
    description: "Sales Manager",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Dominik Doudny",
    description: "Pre-sales Consultant",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
  {
    name: "Malin Quist",
    description: "Sales Manager",
    image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  },
];

const TEST_COMPETITORS = [
  {
    name: "Samsung Group",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Dell Technologies Inc.",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Sony Corporation",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Panasonic Corporation",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
];

const TEST_SUPPLIERS = [
  {
    name: "3M Company",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "AAC Technologies",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "LG Innotek Company Limited",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Hitachi Limited",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Intel Corporation",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Hewlett-Packard",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
];

const TEST_PRODUCTS = [
  {
    name: "Laboriosam itaque",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Voluptatem ut",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Autem voluptatem totam",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Facilis nulla sunt",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
  {
    name: "Aut deleniti culpa",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQFeD2stV0OSRQ/company-logo_200_200/0?e=2159024400&v=beta&t=ajoywrBdyPArf5gpBHxGJoOptqwD1Mz0rMtd6w2jaPQ",
  },
];

const TEST_SALES_HIERARCHY = [
  {
    title: "Apple - Global BU",
    key: '1',
    children: [
      { title: "Apple - AsiaPAC BU", key: '2', },
      {
        title: "Apple - Europe BU",
        key: '3',
        children: [{ title: "Apple - node1", key: '5', }, { title: "Apple - node2", key: '6', }],
      },
      {
        title: "Apple - North America BU",
        key: '4',
        children: [
          {
            title: "Apple - USA",
            key: '7',
            children: [
              { title: "Laredo", key: '8', },
              { title: "Detroit", key: '9', },
              { title: "Columbus", key: '10', },
            ],
          },
        ],
      },
    ],
  },
] as TreeNodeType[];

const TEST_CHART_DATA = {
  labels: ['JUL', '', 'AUG', '', 'SEP', '', 'OCT'],
  datasets: [
    {
      data: [73000, 55000, 60500, 84000, 44000, 73000, 80500],
      backgroundColor: [
        'rgba(232, 153, 129, .3)',
        'rgba(232, 153, 129, .3)',
        'rgba(232, 153, 129, .3)',
        '#E89981',
        'rgba(232, 153, 129, .3)',
        'rgba(232, 153, 129, .3)',
        'rgba(232, 153, 129, .3)'
      ],
    },
  ],
}

const TEST_HISTORY = [
  {userName: 'Andries Grootoonk', action: 'checked', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Gary Washington', action: 'viewed', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Leo Knight', action: 'viewed', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Alex Edwards', action: 'updated', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Jordi Santiago', action: 'updated', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Cha Ji-Hun', action: 'viewed', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Sanne Viscaal', action: 'checked', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Rahul Malviya', action: 'viewed', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Jeremías Romero', action: 'viewed', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Harsha Buksh', action: 'updated', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
  {userName: 'Andries Grootoonk', action: 'checked', actionTime: '09.27.2017 - 9:55:39 AM', userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'},
] as HistoryItem[]

const NEW_ACTIONS = [
  {id: 'edit', onClick: () => {}, title: 'Editing', iconStyle: s.edit_icon },
  {id: 'suggest', onClick: () => {}, title: 'Suggesting', iconStyle: s.suggest_icon },
  {id: 'veiw', onClick: () => {}, title: 'Viewing', iconStyle: s.view_icon },
  {id: 'delete', onClick: () => {}, title: 'Delete', iconStyle: s.delete_icon }
]

export const CustomerDetailsPage = () => {
  const [customer, setCustomer] = useState(undefined as any);
  const [employeeList, setEmployeeList] = useState([] as ListItem[]);
  const [accountTeamList, setAccountTeamList] = useState([] as ListItem[]);
  const [competitorsList, setCompetitorsList] = useState([] as ListItem[]);
  const [suppliersList, setSuppliersList] = useState([] as ListItem[]);
  const [productsList, setProductsList] = useState([] as ListItem[]);
  const [salesHierarchy, setSalesHierarchy] = useState([] as TreeNodeType[]);

  useEffect(() => {
    setCustomer({ ...TEST_DATA });
    setEmployeeList(TEST_EMPLOYEE_LIST);
    setAccountTeamList(TEST_ACCOUNT_TEAN);
    setSuppliersList(TEST_SUPPLIERS);
    setCompetitorsList(TEST_COMPETITORS);
    setProductsList(TEST_PRODUCTS);
    setSalesHierarchy(TEST_SALES_HIERARCHY);
  }, []);

  return (
    <div className={s.container}>
      {customer && (
        <div className={s.panel}>
          <Panel classNames={classnames(s.main, s.panel)}>
            <div className={s.main_header}>
              <div className={s.main_logo_container}>
                <img src={customer.logo} alt="" className={s.main_logo} />
              </div>
              <div className={s.main_header_info}>
                <p>
                  {customer.partyType === '2'
                    ? customer.organizationName
                    : customer.firstGivenName}
                </p>
                <Tag
                  type="blue"
                  fill={true}
                  title={
                    customer.partyType === '2'
                      ? "Organization"
                      : "Person"
                  }
                />
              </div>
              <DropdownButton actions={NEW_ACTIONS} color='blue' defaultAction={NEW_ACTIONS[2]} dropToNull={false} />
            </div>
            <div className={s.columns}>
              <div>
                <p className={s.main_subheader}>Key Financial Figures</p>
                <div className={classnames(s.main_info, s.large_margin)}>
                  <p>
                    <span className={s.main_info_title}>Revenue: ‎‎</span>
                    {customer.revenue}
                  </p>
                  <p>
                    <span className={s.main_info_title}>Locations: ‎‎‎</span>
                    {customer.locations}
                  </p>
                  <p>
                    <span className={s.main_info_title}>Net income‎: ‎‎‎</span>
                    {customer.netIncome}
                  </p>
                </div>
                <div className={s.main_info}>
                  <p>
                    <span className={s.main_info_title}>
                      Auto-generated Sequencial‎: ‎‎
                    </span>
                    {customer.autoGeneratedSequencial}
                  </p>
                  <p>
                    <span className={s.main_info_title}>Name: ‎‎</span>
                    {customer.name}
                  </p>
                  <p>
                    <span className={s.main_info_title}>EntityURI: ‎</span>
                    {customer.entityUri}
                  </p>
                  <p>
                    <span className={s.main_info_title}>
                      Doing Business As Name‎: ‎‎
                    </span>
                    {customer.businessName}
                  </p>
                  <p>
                    <span className={s.main_info_title}>Website URL: </span>
                    {customer.websiteUrl}
                  </p>
                </div>
                <div className={s.main_info}>
                  <p>
                    <span className={s.main_info_title}>Is Subsidiary: ‎</span>
                    {customer.isSubsidiary}
                  </p>
                  <p>
                    <span className={s.main_info_title}>DUNS Number: ‎</span>
                    {customer.duns}
                  </p>
                </div>
                <div>
                  <p>
                    <span className={s.main_info_title}>Company Type: ‎</span>
                    {customer.companyType}
                  </p>
                  <p>
                    <span className={s.main_info_title}>Ticker: ‎</span>
                    {customer.ticker}
                  </p>
                </div>
              </div>
              <div>
                <p className={s.main_subheader}>Address</p>
                <div className={s.main_info_highlighted}>
                  <p>{`${customer.postalCode} ${customer.cityName}, ${customer.stateProvince}, ${customer.countryName}`}</p>
                  <p>{customer.addressLine1}</p>
                </div>
                <p className={s.main_subheader}>Phone</p>
                <div className={s.main_info_highlighted}>
                  <p>{customer.phone}</p>
                  <p>{customer.phoneFaxNumber}</p>
                </div>
              </div>
            </div>
          </Panel>
          <div className={s.panel}>
            <Panel classNames={s.panel}>
              <ListComponent
                title="Employees"
                list={employeeList}
                showTotal={true}
                actions={[]}
                info={<div></div>}
                itemSize="medium"
                maxVisibleItems={5}
              />
            </Panel>
            <Panel classNames={s.panel}>
              <ListComponent
                title="Account Team"
                list={accountTeamList}
                showTotal={true}
                actions={[]}
                info={<div></div>}
                itemSize="medium"
                maxVisibleItems={5}
              />
            </Panel>
          </div>
          <div className={s.panel}>
            <Panel classNames={s.panel}>
              <ListComponent
                title="Competitors"
                list={competitorsList}
                showTotal={true}
                actions={[]}
                info={<div></div>}
                itemSize="small"
                maxVisibleItems={6}
              />
            </Panel>
            <Panel classNames={s.panel}>
              <ListComponent
                title="Suppliers"
                list={suppliersList}
                showTotal={true}
                actions={[]}
                info={<div></div>}
                itemSize="small"
                maxVisibleItems={6}
              />
            </Panel>
          </div>
        </div>
      )}
      {customer && (
        <div>
          <div className={s.panel}>
            <div className={s.panel}>
              {customer.potencialMatches &&
                customer.potencialMatches.length > 0 && (
                  <Panel classNames={s.panel}>
                    <ListTitle title="Potencial Matches" />
                    <div className={s.potencial_matches_container}>
                      <div className={s.potencial_matches_content}>
                        <img
                          src={customer.potencialMatches[0].logo}
                          alt=""
                          className={s.potencial_matches_logo}
                        />
                        <div className={s.potencial_matches_info}>
                          <p>{customer.potencialMatches[0].name}</p>
                          <Tag
                            title={customer.potencialMatches[0].type}
                            type="blue"
                            fill={true}
                          />
                        </div>
                      </div>
                      <Button
                        title="Company Details"
                        type="blue"
                        onClick={() => {}}
                      />
                      <Button
                        title="More Matches"
                        type="blue"
                        onClick={() => {}}
                      />
                    </div>
                  </Panel>
                )}
              <Panel classNames={s.panel}>
                <ListTitle title="Key Financial Figures Overview" />
                <div className={s.chart_container}>
                  <Bar
                    data={TEST_CHART_DATA}
                    options={{
                      legend: {
                        display: false
                      },
                      scales: {
                        yAxes: [
                          {
                            ticks: {
                              beginAtZero: true,
                            },
                          },
                        ],
                      },
                    }}
                    height={300}
                    width={260}
                  />
                </div>
              </Panel>
            </div>
            <Panel classNames={s.panel}>
              <ListTitle title="History" />
              <HistoryList list={TEST_HISTORY} showCurrentView={true} />
            </Panel>
          </div>
          <div className={s.panel}>
            <Panel classNames={s.panel}>
              <ListTitle title="Sales Hierarchy" />
              <SimpleTree nodes={salesHierarchy} showTotal={true} />
            </Panel>
            <Panel classNames={s.panel}>
              <ListTitle title="DnB Hierarchy" />
              <SimpleTree nodes={salesHierarchy} showTotal={true} />
            </Panel>
          </div>
          <Panel classNames={s.panel}>
            <ListComponent
              title="Products"
              list={productsList}
              showTotal={true}
              actions={[]}
              info={<div></div>}
              itemSize="small"
              maxVisibleItems={6}
            />
          </Panel>
        </div>
      )}
    </div>
  );
};
